### ISSUE TITLE
why do you use Session for authenticaion

### ISSUE THREAD

**Issue by fizz12344321** [babl-ws/babl#116]
Hi, i love your repository. Why do you use "Session" in this project, why don't you use other authentications ? and what is "IPC", "multicast network" here
![xoa1](https://user-images.githubusercontent.com/41360493/178033873-cb402682-b0a2-447c-94cc-79fe78d06dac.JPG)

**Comment by epickrram** [comment]
`IPC` = [inter-process communication](https://en.wikipedia.org/wiki/Inter-process_communication) (in this case the Aeron IPC transport).
We use Aeron IPC in place of the Disruptor. They provide similar capabilities, but Aeron allows communication between different Java processes. The Disruptor requires that consumers run within the same memory space as producers.
