### ISSUE TITLE
ask about this picture

### ISSUE THREAD

**Issue by fizz12344321** [babl-ws/babl#117]
Hi, why need you to build the Network like this, what is business logic, receiver and sender, thanks
![xoa2](https://user-images.githubusercontent.com/41360493/178135345-290250ed-aac1-4799-b79d-44c575d132da.JPG)

**Comment by epickrram** [comment]
Closing, as not related to this repository.

**Comment by epickrram** [comment]
That image was originally presented (in a similar format) in this talk:

https://www.youtube.com/watch?v=-6nrhSdu--s

Some of your questions might be answered in the talk.
