### ISSUE TITLE
why do you use Multi-Topic Broadcast

### ISSUE THREAD

**Issue by fizz12344321** [babl-ws/babl#123]
Hi, can you tell me why you use Multi-Topic Broadcast for your architecture ?

**Comment by epickrram** [comment]
Refer to the documentation on the website:

https://babl.ws/multi_topic_broadcast.html

**Comment by johnboy14** [comment]
Are there any performance limitations to the number of topics on a broadcast? For arguments sake, let's say I had 8,000 potential topics I want to broadcast data across.

**Comment by epickrram** [comment]
Hi @johnboy14 
babl should be able to handle a high number of topics. They are used to lookup a number of subscribed sessions, using an open-addressed hashmap. See [SessionBroadcast](https://github.com/babl-ws/babl/blob/master/src/main/java/com/aitusoftware/babl/websocket/broadcast/SessionBroadcast.java) for details.
